<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>signup_page_header</description>
   <name>login_page_header</name>
   <tag></tag>
   <elementGuidId>03918da4-9bb9-4946-a413-9031988921ba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;signInModal&quot;]/div/div/div[1]/h5</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
