<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>signup_page_header</description>
   <name>signup_page_header</name>
   <tag></tag>
   <elementGuidId>7228b4e7-2559-4937-96ef-4c364467ce96</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;signInModal&quot;]/div/h5</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
